var mdp_grammar = {
  "origin": "#sentence#",
  "sentence" : [ "#band# is just #band# for people who #descriptor#." ],
  "band" : 
  [
      "Title Fight",
      "Tigers Jaw",
      "Nada Surf",
      "The National",
      "Sun Kil Moon",
      "Pinegrove",
      "Worries",
      "Seasonal",
      "American Football",
      "The Hotelier",
      "Turnover",
      "Man Overboard",
      "Handguns",
      "Knuckle Puck",
      "Joyce Manor",
      "Brand New",
      "Taking Back Sunday",
      "Rise Against",
      "Polar Bear Club",
      "The Menzingers",
      "Mineral",
      "My Bloody Valentine",
      "Elliot Smith",
      "Neutral Milk Hotel",
      "Animal Collective",
      "AC/DC",
      "Nickleback",
      "Tool",
      "Modern Baseball",
      "Alex G",
      "Phish",
      "The Grateful Dead",
      "Kendrick Lamar",
      "Captain We're Sinking",
      "Green Day",
      "Dads",
      "Jank",
      "Bon Iver",
      "Wicca Phase Springs Eternal",
      "Yung Lean",
      "Lil Peep",
      "Danger Incorporated",
      "Paramore",
      "Dashboard Confessional",
      "Fleet Foxes",
      "Anberlin",
      "Circa Survive",
      "Arcade Fire",
      "Radiohead",
      "The Smiths",
      "Against Me!",
      "Death Cab For Cutie",
      "The Front Bottoms",
      "Modest Mouse",
      "Minus The Bear",
      "The Decemberists",
      "The Antlers",
      "Have A Nice Life",
      "Teen Suicide",
      "Jimmy Eat World",
      "Owen",
      "Capn Jazz",
      "You Blew It",
      "Say Anything",
      "Bloc Party",
      "James Blake",
      "Wu Tang Clan",
      "Kanye West",
      "Sorority Noise",
      "Old Gray",
      "La Dispute",
      "Basement",
      "Balance And Composure",
      "The Story So Far",
      "Moose Blood",
      "Jeff Rosenstock",
      "The World Is A Beautiful Place And I Am No Longer Afraid To Die",
      "Foxing",
      "Hella",
      "TTNG",
      "This Town Needs Guns",
      "Death Grips",
      "Motion City Soundtrack",
      "Coheed And Cambria",
      "Queens Of The Stoneage",
      "Into It. Over It.",
      "Citizen",
      "Elvis Depressedly",
      "Trap music™",
      "Emo™",
      "Classic Rock™",
      "Hip hop™",
      "Jazz™",
      "Aerosmith",
      "Led Zeppelin",
      "The Cure",
      "Slowdive",
      "Sigur Ros",
      "The Killers",
      "Drake",
      "Pop music™",
      "My Chemical Romance",
      "Free Throw",
      "Skramz™",
      "Emotional Hardcore™",
      "Metal™",
      "Tool",
      "A Day To Remember",
      "Foo Fighters"
  ],
  "descriptor" : 
  [
      "are really sad all the time",
      "like drinking a lot",
      "wear Nirvana t-shirts",
      "think that Tool is really intelligent music",
      "smoke a lot of weed but never share it",
      "buy crystals",
      "go to church",
      "cuff their jeans and drink PBR",
      "still wear black skinny jeans",
      "go to work in an office every day",
      "love cars",
      "have been to philly once",
      "don't like to listen to folk punk",
      "liked the Foo Fighters in high school",
      "voted for Trump",
      "voted for Hillary",
      "thought Bernie could win the presidency",
      "drink too much",
      "like Tigers Jaw without Adam",
      "think /mu/ is the objective opinion of music",
      "think Anthony Fantano is the only objective opinion of music",
      "think Pitchfork is the only objective opinion of music",
      "are racist",
      "have fake mental illnesses",
      "write code for a living",
      "don't like cussing"
  ]
};